on:
  push:
  pull_request:

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          source-dir: decred/decred-linux-amd64-v2.1.6

      - uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: |
            debian/artifacts/dcrctl_2.1.6-1_amd64.deb
            debian/artifacts/dcrd_2.1.6-1_amd64.deb
            debian/artifacts/dcrwallet_2.1.6-1_amd64.deb
